config/routes.rb
Rails.application.routes.draw do

  resources :categories do
    collection do
      get :manage
      get :nested_options
      get :expand
      get :node_manage

      post :expand_node
      post :rebuild
    end
  end

  root 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  include TheSortableTree::Scopes
  acts_as_nested_set

  # any code here

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include TheSortableTreeController::Rebuild
  include TheSortableTreeController::ExpandNode

  def index
    @pages = Category.nested_set.select('id, title, content, parent_id').limit(15)
  end

  def nested_options
    @pages = Category.nested_set.select('id, title, content, parent_id').limit(15)
  end

  def manage
    @pages = Category.nested_set.select('id, title, content, parent_id').all
  end

  def node_manage
    @root  = Category.root
    @pages = @root.self_and_descendants.nested_set.select('id, title, content, parent_id').limit(15)
  end

  def expand
    @pages = Category.nested_set.roots.select('id, title, content, parent_id').all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/expand.html.erb
<p><%= link_to raw('&larr; back'), '/' %></p>
<p><%= link_to 'Create New Page', "#" %></p>

<p>Count: <%= @pages.to_a.count %></p>

<ol class="sortable_tree expandable" data-max_level="5" data-rebuild_url="<%= rebuild_categories_url %>", data-expand_node_url="<%= expand_node_categories_url %>" data-cookie_store="true" data-cookie_scope="<%= @pages.first.class %>">
  <%= expandable_tree @pages %>
</ol>

app/views/categories/expand_node.html.erb
<ol class="nested_set"><%=  expandable_tree @children %></ol>

app/views/categories/index.html.erb
<p><%=  link_to raw('&larr; back'), '/' %></p>

<ol class='tree'> <%=  just_tree @pages %></ol>

app/views/categories/manage.html.erb
<p><%= link_to raw('&larr; back'), '/' %></p>

<ol class="sortable_tree" data-rebuild-url="<%= rebuild_categories_url %>" >
  <%= build_server_tree @pages, :type => :sortable %>
</ol>

app/views/categories/nested_options.html.erb
<p><%=  link_to raw('&larr; back'), '/' %></p>

<%= select_tag :pages, nested_options(@pages, selected: @pages.last), class: :nested_options %>

app/views/categories/node_manage.html.erb
<p><%= link_to raw('&larr; back'), '/' %></p>

<ol class="sortable_tree" data-rebuild-url="#" >
  <%= build_server_tree @pages, :type => :sortable %>
</ol>

<h2>Root:</h2>
<div><%= @root.inspect %></div>
<h2>Root's children:</h2>
<div><%= @pages.inspect %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsNestedSetModel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to Nested Category Pages test application!</h1>

<h5>Category Pages (model Pages)</h5>

<ul>
  <li><%= link_to 'categories/index (just tree)',           categories_path %></li>
  <li><%= link_to 'categories/nested_options',              nested_options_categories_path %></li>
  <li><%= link_to 'categories/manage (sortable tree)',      manage_categories_path %></li>
  <li><%= link_to 'categories/node_manage (sortable tree)', node_manage_categories_path %></li>
  <li><%= link_to 'categories/expand (expandable tree)',    expand_categories_path %></li>
</ul>